config/routes.rb
Rails.application.routes.draw do
  resources :dogs

   root 'pages#home'

   get '/login' => 'sessions#new'
   post '/login' => 'sessions#create'
   get '/logout' => 'sessions#destroy'

   get '/signup' => 'users#new'
   post '/users' => 'users#create'

   

end

app/models/dog.rb
class Dog < ActiveRecord::Base
  has_attached_file :image, styles: { large: "500x500>", medium: "300x300>", thumb: "150x150>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  #alternative search method
    #scope :by_name, -> (name) { where name: name }
    #scope :by_gender, -> (gender) { where gender: gender }
    #scope :by_breed, -> (breed) { where breed: breed }

  def self.search(search)
  	#Rails 4.2 will only return the LAST where results if listed on separate lines
    #Postgres's ILIKE below replaced LIKE to create case-insensitive search
    # "%" + search + "%" to prevent SQL injection
    where("name ILIKE ? OR breed ILIKE ? OR gender ILIKE ?", "%" + search + "%", "%" + search + "%", "%" + search + "%")# will work
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  #helper_method allows us to use @current_user in view files.
  helper_method :current_user

  def authorize
  	redirect_to '/login' unless current_user
  end

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :authorize, only: [:new, :edit, :update, :destroy]
  before_action :set_dog, only: [:show, :edit, :update, :destroy]


  # GET /dogs
  # GET /dogs.json
  #def index
    #@dogs = Dog.all
    #@dogs = Dog.where(nil) # creates an anonymous scope
    #@dogs = @dogs.by_name(params[:name]) if params[:name].present?
    #@dogs = @dogs.by_breed(params[:breed]) if params[:breed].present?
    # gender search not yet working
    # @dogs = @dogs.by_gender(params[:gender]) if params[:gender].present?
  #end

  def index
      #@dogs = Dog.all
      if params[:search]
        @dogs = Dog.search(params[:search]).order("created_at DESC")
      else
       @dogs = Dog.all.order("created_at DESC")
      end
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'New dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'This dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'This entry was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:image, :name, :age, :gender, :breed, :secondary_breed, :heartworm_status, :temperament, :activity_level, :info, :available, :contact_name, :contact_phone)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	#https://gist.github.com/thebucknerlife/10090014

	def new
	end

	def create
		user = User.find_by_email(params[:email])
		#if user exists and password provided is correct
		if user && user.authenticate(params[:password])
			#save user id in browser cookie, so that login persists throughout site
			session[:user_id] = user.id
			redirect_to '/'
		else
			#if user's login does not work, return to login form
			flash[:error] = 'An error occured!'
			redirect_to '/login'
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to '/login'
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
	end

	def create
		user = User.new(user_params)
		if user.save
			session[:user_id] = user.id
			redirect_to '/', notice: 'Account created successfully'
			#redirect_to '/'
		else
			flash[:error] = 'An error occured!'
			redirect_to '/signup'
		end
	end

	private

		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dogs/_form.html.erb
<%= form_for @dog, html: { multipart: true } do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :secondary_breed %><br>
    <%= f.text_field :secondary_breed %>
  </div>
  <div class="field">
    <%= f.label :heartworm_status %><br>
    <%= f.text_field :heartworm_status %>
  </div>
  <div class="field">
    <%= f.label :temperament %><br>
    <%= f.text_field :temperament %>
  </div>
  <div class="field">
    <%= f.label :activity_level %><br>
    <%= f.text_field :activity_level %>
  </div>
  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_area :info %>
  </div>
  <div class="field">
    <%= f.label :available %><br>
    <%= f.date_select :available %>
  </div>
  <div class="field">
    <%= f.label :contact_name %><br>
    <%= f.text_field :contact_name %>
  </div>
  <div class="field">
    <%= f.label :contact_phone %><br>
    <%= f.text_field :contact_phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<header>
  <h1>Available Dogs</h1>
    <%= form_tag(dogs_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search for..." %>
    <%= submit_tag "Find Dogs" %>
    <% end %>
</header>

<% if @dogs.present? %>

<table class="show-xs">
  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <!-- <td class="tbl-img"><%= link_to image_tag dog.image.url (:thumb)%></td>  -->
        <td class="twenty-five left"><%= image_tag dog.image.url, width:110, height:80 %></td>
        <td class="thirty-five"><%= link_to 'About ' + dog.name , dog %></td>
        <td class="fifteen"><%= dog.age %></td>
        <td class="twenty-five"><%= dog.gender %></td>
        
        <% if current_user %>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
</div>


<div class="hide-xs">
  <div class="center">
  <% @dogs.each do |dog| %>
          <div class="card">
            <div class="card-image">
              <p><%= link_to image_tag dog.image.url (:medium)%></p>
            </div>
      
            <div class="card-title">
              <p><%= dog.name %></p>
            </div>
            
            <div class="card-action">
              <div class="age">
                  <p><%= dog.age %></p>
              </div>
                <% if dog.gender == "male" || dog.gender == "Male" %>
                      <div class="gender male">
                        <p>M</p>
                       </div>
                <% elsif dog.gender == "female" || dog.gender == "Female" %>
                    <div class="gender female">
                     <p>F</p>
                    </div>
                <% end %>
              <div class="dog-link">
                  <p><%= link_to dog.name + "'s Info", dog %></p>
              </div>
            </div><!--/card-action-->
          </div>
      <% end %> 
  </div><!--/card-->
  </div><!--/center-->
</div><!--/hide-xs-->


  

<% else %>
  <p> Sorry, no dogs matched the term "<%= params[:search] %>".</p>
  <%= link_to 'View All Dogs', dogs_path %>
<% end %>

<br>

<% if current_user %>
<%= link_to 'Create New Dog Entry', new_dog_path %>
<% end %>

app/views/dogs/new.html.erb
<h1>New dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="flex">
  <div class="img-show">
    <%=image_tag @dog.image.url(:large), class:'img-contain' %>
  </div>

      <h1 class="hello">Hi, I'm <%= @dog.name %> </h1>
      <div class="beside-photo">
        <p class="paragraph"> <%= @dog.info %> </p>
      </div>
  
  <div class="info">
      <table class="show">
        <tbody>
        <!-- <tr class="stats">
          <td>Name:</td>
          <td> <%= @dog.name %> </td>
        </tr> -->
        <tr class="stats">
          <td>Age:</td>
          <td><%= @dog.age %></td>
          
        </tr>
        <tr class="stats">
          <td>Gender:</td>
          <td><%= @dog.gender %></td>
          
        </tr>
        <tr class="stats">
          <td>Main Breed:</td>
          <td><%= @dog.breed %></td>
        </tr> 
        <tr class="stats">
          <td>Secondary Breed:</td>
          <td><%= @dog.secondary_breed %></td>
        </tr> 
        <tr class="stats">
          <td>Heartworm Status:</td>
          <td><%= @dog.heartworm_status %></td>
        </tr>
        <tr class="stats">
          <td>Temperament:</td>
          <td><%= @dog.temperament %></td>
        </tr> 
        <tr class="stats">
          <td>Activity Level:</td> 
          <td><%= @dog.activity_level %></td>
        </tr>
        <tr class="stats">
          <td>Available On:</td>
          <td><%= @dog.available.strftime("%B %d, %Y") %></td>
        </tr>
        <tr class="stats highlight-blue blurb">
          <td colspan="2"><%= @dog.info %></td>
        </tr>

        <tr class="stats highlight-yellow">
          <td>Contact:</td>
          <td><%= @dog.contact_name %></td>
        </tr>
        <tr class="stats highlight-yellow">
          <td>Phone:</td>
          <td><%= @dog.contact_phone %></td>
        </tr>
        <tr class="stats highlight-turq">
          <td colspan="2"><%= link_to 'Back to Available Dogs', dogs_path, class: 'back-to' %></td>
        </tr>
        </tbody>
      </table>
    </div><!--/info-->

    <div class="extra-pix">
      <img src="http://placehold.it/350x200">
      <img src="http://placehold.it/350x200">
    </div>
  </div><!--/flex-->

      <% if current_user %>
          <%= link_to 'Edit', edit_dog_path(@dog) %> |
      <% end %> 

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DogRescue</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
   <body>

	<div class="container">
			
		<%= yield %>

	</div><!--/container-->
		
	</body>
</html>

app/views/pages/home.html.erb
<h1>This is the homepage...for now.</h1>

<footer>
			<% if current_user %>
		  		Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
			<% else %>
		  		<%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
			<% end %>
		</footer>

app/views/users/new.html.erb
<h1>Create Admin Account</h1>

<%= form_for :user, url: '/users' do |f| %>

Name: <%= f.text_field :name %>
Email: <%= f.text_field :email %>
Password: <%= f.password_field :password %>
Password Confirmation: <%= f.password_field :password_confirmation %>
<%= f.submit "Submit" %>

<% end %>